export const COMMENTS = [
  {
    id: 0,
    campsiteId: 0,
    rating: 5,
    text: "ኣደ ህይወት ኣደ ክርስቶስ!",
    author: "D.Manna",
    date: "2021-06-03T16:30Z",
  },
  {
    id: 1,
    campsiteId: 0,
    rating: 4,
    text: "ኦ ጎይታ ብመንግስትኻ ምስ እትመጽእ ዘክረኒ!",
    author: "D.Natu",
    date: "2021-06-03T03:33Z",
  },
  {
    id: 2,
    campsiteId: 0,
    rating: 5,
    text: "እግዚኣብሔርሰ ገሃደ ይመጽእ፡ ወኣምላክነሂ ኢያረምም፡ እሳት ይነድድ ቅድሜሁ!",
    author: "D.Manna",
    date: "2021-06-03T18:12Z",
  },
  {
    id: 3,
    campsiteId: 0,
    rating: 5,
    text: "እግዚኣብሔርሰ ገሃደ ይመጽእ፡ ወኣምላክነሂ ኢያረምም፡ እሳት ይነድድ ቅድሜሁ!",
    author: "D.Manna",
    date: "2019-08-04T20:11Z",
  },
  {
    id: 4,
    campsiteId: 0,
    rating: 4,
    text: "እግዚኣብሔርሰ ገሃደ ይመጽእ፡ ወኣምላክነሂ ኢያረምም፡ እሳት ይነድድ ቅድሜሁ!",
    author: "D.Manna",
    date: "2018-07-23T19:44Z",
  },
  {
    id: 5,
    campsiteId: 1,
    rating: 4,
    text: "እግዚኣብሔርሰ ገሃደ ይመጽእ፡ ወኣምላክነሂ ኢያረምም፡ እሳት ይነድድ ቅድሜሁ!",
    author: "D.Manna",
    date: "2017-06-17T03:33Z",
  },
  {
    id: 6,
    campsiteId: 1,
    rating: 5,
    text: "እግዚኣብሔርሰ ገሃደ ይመጽእ፡ ወኣምላክነሂ ኢያረምም፡ እሳት ይነድድ ቅድሜሁ!",
    author: "D.Manna",
    date: "2019-02-18T18:12Z",
  },
  {
    id: 7,
    campsiteId: 1,
    rating: 5,
    text: "እግዚኣብሔርሰ ገሃደ ይመጽእ፡ ወኣምላክነሂ ኢያረምም፡ እሳት ይነድድ ቅድሜሁ!",
    author: "D.Manna",
    date: "2019-08-04T20:11Z",
  },
  {
    id: 8,
    campsiteId: 1,
    rating: 4,
    text: "እግዚኣብሔርሰ ገሃደ ይመጽእ፡ ወኣምላክነሂ ኢያረምም፡ እሳት ይነድድ ቅድሜሁ!",
    author: "Ann Dabramov",
    date: "2018-07-23T19:44Z",
  },
  {
    id: 9,
    campsiteId: 1,
    rating: 5,
    text: "እግዚኣብሔርሰ ገሃደ ይመጽእ፡ ወኣምላክነሂ ኢያረምም፡ እሳት ይነድድ ቅድሜሁ!",
    author: "D.Natu",
    date: "2018-10-25T16:30Z",
  },
  {
    id: 10,
    campsiteId: 2,
    rating: 5,
    text: "እግዚኣብሔርሰ ገሃደ ይመጽእ፡ ወኣምላክነሂ ኢያረምም፡ እሳት ይነድድ ቅድሜሁ!",
    author: "D.Natu",
    date: "2019-02-18T18:12Z",
  },
  {
    id: 11,
    campsiteId: 2,
    rating: 5,
    text: "እግዚኣብሔርሰ ገሃደ ይመጽእ፡ ወኣምላክነሂ ኢያረምም፡ እሳት ይነድድ ቅድሜሁ!",
    author: "D.Natu",
    date: "2019-08-04T20:11Z",
  },
  {
    id: 12,
    campsiteId: 2,
    rating: 4,
    text: "እግዚኣብሔርሰ ገሃደ ይመጽእ፡ ወኣምላክነሂ ኢያረምም፡ እሳት ይነድድ ቅድሜሁ!",
    author: "D.Natu",
    date: "2018-07-23T19:44Z",
  },
  {
    id: 13,
    campsiteId: 2,
    rating: 5,
    text: "እግዚኣብሔርሰ ገሃደ ይመጽእ፡ ወኣምላክነሂ ኢያረምም፡ እሳት ይነድድ ቅድሜሁ!",
    author: "D.Natu",
    date: "2018-10-25T16:30Z",
  },
  {
    id: 14,
    campsiteId: 2,
    rating: 4,
    text: "እግዚኣብሔርሰ ገሃደ ይመጽእ፡ ወኣምላክነሂ ኢያረምም፡ እሳት ይነድድ ቅድሜሁ!",
    author: "D.Natu",
    date: "2017-06-17T03:33Z",
  },
  {
    id: 15,
    campsiteId: 3,
    rating: 5,
    text: "ኦ ጎይታ ብመንግስትኻ ምስ እትመጽእ ዘክረኒ!",
    author: "D.Natu",
    date: "2019-08-04T20:11Z",
  },
  {
    id: 16,
    campsiteId: 3,
    rating: 4,
    text: "ኦ ጎይታ ብመንግስትኻ ምስ እትመጽእ ዘክረኒ!",
    author: "D.Natu",
    date: "2018-07-23T19:44Z",
  },
  {
    id: 17,
    campsiteId: 3,
    rating: 5,
    text: "ኦ ጎይታ ብመንግስትኻ ምስ እትመጽእ ዘክረኒ!",
    author: "D.Natu",
    date: "2018-10-25T16:30Z",
  },
  {
    id: 18,
    campsiteId: 3,
    rating: 4,
    text: "ኦ ጎይታ ብመንግስትኻ ምስ እትመጽእ ዘክረኒ!",
    author: "D.Natu",
    date: "2017-06-17T03:33Z",
  },
  {
    id: 19,
    campsiteId: 3,
    rating: 5,
    text: "ኦ ጎይታ ብመንግስትኻ ምስ እትመጽእ ዘክረኒ!",
    author: "D.Natu",
    date: "2019-02-18T18:12Z",
  },
];
